link:
  forward: TIO_000037
  reverse: TIO_000036
  file: sample.tsv
update:
  frequency: Quarterly
  method: sparql_taxon.rb query.rq https://integbio.jp/rdf/ebi/sparql $TOGOID_ROOT/input/ensembl/taxonomy.txt
