source:
  namespace: dgidb
  type: drug-gene interactions
  label: DGIdb ID
  prefix: http://identifiers.org/dgidb/interaction/

target:
  namespace: ncbigene
  type: Gene
  label: NCBI Gene
  prefix: http://identifiers.org/ncbigene/

link:
  file: pair.tsv

  forward:
    namespace: rdfs
    label: NCBI Gene ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency:
  method: dgidb-ncbigene.sh > pair.tsv
