link:
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: sample.tsv
update:
  frequency: freeze
  method: sparql_csv2tsv.sh query.rq https://orth.dbcls.jp/sparql-dev
