source:
  label: Affymetrix Probeset
  namespace: affy.probeset
  type: Gene
  prefix: http://identifiers.org/affy.probeset/
target:
  label: NCBI gene
  namespace: ncbigene
  type: Gene
  prefix: http://identifiers.org/ncbigene/
link:
  file: pair.tsv
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: freeze
  method: update.sh > pair.tsv
