source:
  namespace: chembl.target
  type: Protein
  label: ChEMBL target
  prefix: http://rdf.ebi.ac.uk/resource/chembl/targetcomponent/

target:
  label: GO
  type: Gene
  name: GO
  prefix: http://identifiers.org/obo.go/

link:
  file: pair.tsv

  forward:
    namespace: rdfs
    label: Protein2Gene
    #Sparqlクエリに合わせてこのprefix/predicateにしたが、タンパク質→遺伝子ならもっと適切なものが絶対あると思う。
    #Sparqlクエリに合わせるのか、ROからsource ofみたいなのを見つけて当てがうか、どちらがいいのか。
    prefix: http://rdf.ebi.ac.uk/terms/chembl#
    predicate: targetCmptXref

update:
  frequency: Monthly
  method: https://is.gd/7CuouX
