source:
  label: Orphanet Rare Disease Ontology
  type: Disease
  namespace: ORPHA
  prefix:	http://identifiers.org/orphanet/

target:
  label: HGNC
  type: Gene
  namespace: HGNC
  prefix: http://identifiers.org/hgnc/

link:
  file: pair.tsv

  forward:
    label: Related ID of ORDO
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

  reverse:
    label: Related ID of HGNC
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: not stable
  method: ordo_hgnc.bash