link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.pl
