source:
  namespace: interpro
  type: Protein family
  label: InterPro
  prefix: http://identifiers.org/interpro/
target:
  namespace: go
  type: Function
  label: Gene Ontology
  prefix: http://identifiers.org/go/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: functionally related to
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002328
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Bimonthly
  method: curl -sS ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro2go | awk '!/^!/{print gensub("InterPro:","","g",$1) "\t" gensub(/[^;]*; /,"","g")}' > pair.tsv
