link:
  forward: TIO_000124
  reverse: TIO_000125
  file: sample.tsv
update:
  frequency: Monthly
  method: gzip -dc $TOGOID_ROOT/input/refseq_protein/gene_refseq_uniprotkb_collab.gz | awk -F "\t" '!/^#/ && !a[$1]++{print gensub(/\.[0-9]+$/,"","g",$1) "\t" $3}'
