link:
  forward: TIO_000142
  reverse: TIO_000143
  file: sample.tsv
update:
  frequency: Monthly
  method: gzip -dc ${TOGOID_ROOT}/input/uniprot/idmapping.dat.gz | awk -F "\t" '$1~/-/&&!a[$1]++{print gensub(/-[0-9]+/,"","g",$1) "\t" $1}'
