link:
  forward: TIO_000002
  reverse: TIO_000002
  file: sample.tsv
update:
  frequency: Monthly
  method: gzip -dc ${TOGOID_ROOT}/input/uniparc/uniparc*.tsv.gz | awk -F "\t" '$2=="RefSeq"{print $1 "\t" $3}'
