link:
  file: sample.tsv
  forward: TIO_000094
  reverse: TIO_000095
update:
  frequency: Monthly
  method: curl https://ddbj.nig.ac.jp/public/rdf/dblink/insdc_master-biosample/insdc_master2biosample.tsv
