source:
  namespace: drugbank
  label: DrugBank
  type: Drug
  prefix: http://identifiers.org/drugbank

target:
  namespace: pubmed
  label: PubMed
  type: 
  prefix: http://bio2rdf.org/pubmed

link:
  file: pair.tsv

  forward:
    namespace: pubmed.id
    label: PubMed ID
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_HOM0002558  # has evidence

update:
  frequency: Monthly
  method: #wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
