link:
  file: sample.tsv
  forward: TIO_0000XX
  reverse: TIO_0000XX
update:
  frequency: Monthly
  method: curl -s https://ddbj.nig.ac.jp/public/rdf/dblink/assembly_genome-insdc/assembly_genome2insdc.tsv
