source:
  namespace: drugbank
  label: DrugBank
  type: Drug
  prefix: http://identifiers.org/drugbank

target:
  namespace: uniprot
  label: UniProt
  type: Protein
  prefix: http://purl.uniprot.org/core/

link:
  file: pair.tsv

  forward:
    namespace: uniprot.id
    label: UniProtKB ID
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_HOM0000071  # in homotopy relationship with

update:
  frequency: Monthly
  method: #wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
