link:
  file: sample.tsv
  forward: TIO_xxxxxx
  reverse: TIO_xxxxxx
update:
  frequency: Monthly
  method: "wget https://ddbj.nig.ac.jp/public/rdf/dblink/jga_study-jga_dataset/jga_study2jga_dataset.tsv"
