source:
  namespace: doid
  type: Disease
  label: Human Disease Ontology
  prefix: http://purl.obolibrary.org/obo/
target:
  namespace: kegg
  type: Pathway
  label: Kegg Pathway
  prefix: https://identifiers.org/kegg.pathway
link:
  file: link.tsv
  forward:
    label: Related ID of Kegg Pathway
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    label: Related ID of DOID
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency:
  method: doid-kegg.sh > link.tsv
